#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

set -o allexport; source .env.local; set +o allexport

python /app/manage.py collectstatic --settings=pythonDjango.settings.development --noinput

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
