#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

set -o allexport; source .env.local; set +o allexport
echo "Starting Django REST API"
python /app/manage.py makemigrations pythonDjango --settings=pythonDjango.settings.development
python /app/manage.py migrate --settings=pythonDjango.settings.development
python /app/manage.py runserver --settings=pythonDjango.settings.development 0.0.0.0:5000
