export default function AppHead() {
  return (
    <>
      <title>Star Wars Demo</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href='RedHat_favicon_0319.png' />
    </>
  )
}
